//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EateryManager.Web.Vips {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblVipID;
		protected global::System.Web.UI.WebControls.TextBox txtVipName;
		protected global::System.Web.UI.WebControls.TextBox txtVipSex;
		protected global::System.Web.UI.WebControls.TextBox txtVGID;
		protected global::System.Web.UI.WebControls.TextBox txtVipTel;
		protected global::System.Web.UI.WebControls.TextBox txtVipStartDate;
		protected global::System.Web.UI.WebControls.TextBox txtVipEndDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
