//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EateryManager.Web.Vips {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblVipID;
	protected global::System.Web.UI.WebControls.Label lblVipName;
	protected global::System.Web.UI.WebControls.Label lblVipSex;
	protected global::System.Web.UI.WebControls.Label lblVGID;
	protected global::System.Web.UI.WebControls.Label lblVipTel;
	protected global::System.Web.UI.WebControls.Label lblVipStartDate;
	protected global::System.Web.UI.WebControls.Label lblVipEndDate;


       
    }
}
