//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EateryManager.Web.ConsumerDetails {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblCDID;
		protected global::System.Web.UI.WebControls.TextBox txtCBID;
		protected global::System.Web.UI.WebControls.TextBox txtProductID;
		protected global::System.Web.UI.WebControls.TextBox txtCDPrice;
		protected global::System.Web.UI.WebControls.TextBox txtCDNum;
		protected global::System.Web.UI.WebControls.TextBox txtCDSale;
		protected global::System.Web.UI.WebControls.TextBox txtCDMoney;
		protected global::System.Web.UI.WebControls.TextBox txtCDType;
		protected global::System.Web.UI.WebControls.TextBox txtCDDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
