//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EateryManager.Web.ConsumerDetails {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCDID;
	protected global::System.Web.UI.WebControls.Label lblCBID;
	protected global::System.Web.UI.WebControls.Label lblProductID;
	protected global::System.Web.UI.WebControls.Label lblCDPrice;
	protected global::System.Web.UI.WebControls.Label lblCDNum;
	protected global::System.Web.UI.WebControls.Label lblCDSale;
	protected global::System.Web.UI.WebControls.Label lblCDMoney;
	protected global::System.Web.UI.WebControls.Label lblCDType;
	protected global::System.Web.UI.WebControls.Label lblCDDate;


       
    }
}
